---

# Automatically build, validate, and deploy the zookeeper-cdh-docker project

# Build the docker image
verify_build:
  stage: test
  image: maven:3.5.3-jdk-8
  script:
    - ${CI_PROJECT_DIR}/build.sh

deploy:
  stage: deploy
  image: maven:3.5.3-jdk-8
  only:
    - master
    - tags
  script:
    - echo "Building the docker images, tagging as '${CI_COMMIT_TAG}' and 'latest', and pushing to registry..."
    - ${CI_PROJECT_DIR}/build.sh -v "${CI_COMMIT_TAG}" -v "latest" -p
